/**
 * BHARAT MINDS - Option Entry Generator
 * Domain Models and Type Definitions
 * 
 * This file contains all domain models used across the application.
 * These models are framework-independent and represent the core business entities.
 */

// ============================================================================
// BASE CATEGORY AND RESERVATION TYPES
// ============================================================================

/**
 * Base category enum
 * Represents the primary reservation category of a student
 */
export enum BaseCategory {
    CATEGORY_1 = '1G',      // Category 1 General
    CATEGORY_2A = '2AG',    // Category 2A General
    CATEGORY_2B = '2BG',    // Category 2B General
    CATEGORY_3A = '3AG',    // Category 3A General
    CATEGORY_3B = '3BG',    // Category 3B General
    SC = 'SCG',             // Scheduled Caste General
    ST = 'STG',             // Scheduled Tribe General
    GM = 'GM',              // General Merit
}

/**
 * Reservation flags interface
 * Tracks additional reservation benefits eligible to the student
 */
export interface ReservationFlags {
    hasKannada: boolean;     // Kannada medium reservation
    hasRural: boolean;       // Rural area reservation
    hasHK: boolean;          // Hyderabad-Karnataka (371J) reservation
}

/**
 * Complete set of possible category variants
 * Generated by combining base category with reservation flags
 */
export type CategoryVariant = string; // e.g., '2AG', '2AK', '2AR', '2AH', '2AKH', '2ARH'

// ============================================================================
// COUNSELLING TYPES AND COURSES
// ============================================================================

/**
 * Counselling type enum
 */
export enum CounsellingType {
    UGCET = 'UGCET',         // Under Graduate Common Entrance Test
    UGNEET = 'UGNEET',       // NEET for Medical/Dental
    COMBINED = 'COMBINED',   // Both UGCET and UGNEET
}

/**
 * Course types for UGCET
 */
export enum UGCETCourseType {
    ENGINEERING = 'Engineering and Technology',
    ARCHITECTURE = 'Architecture',
    BVSC_AH = 'Bachelor of Veterinary Science and Animal Husbandry',
    FARM_SCIENCE = 'Farm Science',
    PHARMACY = 'B.Pharm',
    PHARMA_D = 'Pharm.D',
    YOGA = 'Bachelor of Yoga and Naturopathy',
    NURSING = 'B.Sc. (Nursing)',
}

/**
 * Course types for UGNEET
 */
export enum UGNEETCourseType {
    MBBS = 'MBBS',
    BDS = 'BDS',
    BAMS = 'BAMS',      // Ayurveda
    BHMS = 'BHMS',      // Homeopathy
    BUMS = 'BUMS',      // Unani
}

/**
 * Seat types - Different for UGCET and UGNEET
 */
export enum SeatType {
    // UGCET Seat Types
    GOVERNMENT = 'G',           // Government seats
    AIDED = 'A',                // Aided seats
    PRIVATE = 'P',              // Private/Unaided seats

    // UGNEET Seat Types
    GOV_UGNEET = 'G',          // Government
    PRIVATE_UGNEET = 'P',      // Private
    MANAGEMENT = 'Q',           // Management/Payment seats
    NRI = 'N',                  // NRI seats
}

/**
 * College type classification
 */
export enum CollegeType {
    GOVERNMENT = 'Government',
    AIDED = 'Aided',
    PRIVATE = 'Private',
    VTU_PRIVATE = 'VTU-Affiliated Private',
    AUTONOMOUS = 'Autonomous',
    DEEMED = 'Deemed University',
    STATE_UNIVERSITY = 'State University',
}

// ============================================================================
// RANK MANAGEMENT
// ============================================================================

/**
 * Student rank entry for a specific course
 */
export interface StudentRank {
    userId: string;
    counsellingType: CounsellingType;
    courseType: string;      // UGCETCourseType or UGNEETCourseType

    // For most courses
    theoryRank?: number;

    // For Farm Science and BVSc & AH only
    practicalScore?: number;

    // For UGNEET
    neetAIR?: number;        // All India Rank

    // Metadata
    createdAt: string;
    updatedAt: string;
}

// ============================================================================
// COLLEGE AND COURSE MANAGEMENT
// ============================================================================

/**
 * College information
 */
export interface College {
    $id: string;
    collegeCode: string;         // Unique code (e.g., E001)
    collegeName: string;
    city: string;                // Karnataka cities
    district: string;
    collegeType: CollegeType;
    counsellingTypes: CounsellingType[];  // Which counselling this college participates in

    // Metadata
    address?: string;
    website?: string;
    established?: number;

    // Comparison Attributes
    latitude?: number;
    longitude?: number;
    averageFees?: number;
    placementRate?: number;
    rating?: number;

    // Indexing
    createdAt: string;
    updatedAt: string;
}

/**
 * Course offered by a college
 * Maps a college to specific courses it offers with available seat types
 */
export interface CollegeCourse {
    $id: string;
    collegeId: string;           // Foreign key to College
    collegeCode: string;         // Denormalized for fast lookup

    courseType: string;          // UGCETCourseType or UGNEETCourseType
    branchName?: string;         // e.g., "Computer Science", "Mechanical"
    branchCode?: string;         // e.g., "CS", "ME"

    availableSeatTypes: SeatType[];  // Seat types available for this course
    totalSeats: number;

    // Metadata
    accreditation?: string;      // NBA, NAAC, etc.
    intake?: number;

    createdAt: string;
    updatedAt: string;
}

// ============================================================================
// USER PROFILE AND ELIGIBILITY
// ============================================================================

/**
 * User profile with eligibility information
 */
export interface UserProfile {
    $id: string;
    userId: string;              // Appwrite auth user ID

    // Personal info
    name: string;
    email: string;
    phone: string;

    // Eligibility information
    baseCategory: BaseCategory;
    reservationFlags: ReservationFlags;
    eligibleCategories: CategoryVariant[];  // Generated deterministically

    // Counselling configuration
    counsellingTypes: CounsellingType[];

    // Profile status
    profileCompleted: boolean;
    ranksEntered: boolean;
    preferencesEntered: boolean;

    // Metadata
    createdAt: string;
    updatedAt: string;
}

// ============================================================================
// PREFERENCE ENTRY (OPTION ENTRY)
// ============================================================================

/**
 * Single option entry in the preference list
 */
export interface OptionEntry {
    priority: number;            // 1-based priority order
    collegeId: string;
    collegeCode: string;         // Denormalized
    collegeName: string;         // Denormalized
    courseType: string;
    branchName?: string;
    branchCode?: string;
    seatType: SeatType;
    category: CategoryVariant;   // Which category this option is for
}

/**
 * User's complete preference list
 */
export interface UserPreferences {
    $id: string;
    userId: string;
    counsellingType: CounsellingType;

    // Ordered list of preferences
    options: OptionEntry[];

    // Metadata
    totalOptions: number;
    lastModified: string;
    isLocked: boolean;           // Lock after submission

    createdAt: string;
    updatedAt: string;
}

// ============================================================================
// VALIDATION AND BUSINESS RULES
// ============================================================================

/**
 * Validation result for preference entry
 */
export interface ValidationResult {
    isValid: boolean;
    errors: string[];
    warnings?: string[];
}

/**
 * Search filters for college search
 */
export interface CollegeSearchFilters {
    collegeCode?: string;
    collegeName?: string;        // Partial match
    city?: string;
    collegeType?: CollegeType;
    counsellingType?: CounsellingType;
    courseType?: string;
}

/**
 * Course availability query result
 */
export interface CourseAvailability {
    collegeId: string;
    collegeCode: string;
    collegeName: string;
    courseType: string;
    branchName?: string;
    branchCode?: string;
    availableSeatTypes: SeatType[];
    totalSeats: number;
}

// ============================================================================
// FUTURE: CUTOFF PREDICTION
// ============================================================================

/**
 * Historical cutoff data (for future prediction engine)
 */
export interface CutoffData {
    $id: string;
    collegeId: string;
    courseId: string;
    category: CategoryVariant;
    seatType: SeatType;
    round: number;
    year: number;
    closingRank: number;

    createdAt: string;
}

/**
 * Seat matrix configuration (for future simulation)
 */
export interface SeatMatrix {
    collegeId: string;
    courseId: string;
    category: CategoryVariant;
    seatType: SeatType;
    totalSeats: number;
    reservedSeats?: number;
}

export default {
    BaseCategory,
    CounsellingType,
    UGCETCourseType,
    UGNEETCourseType,
    SeatType,
    CollegeType,
};
