/**
 * Database Schema Definitions for BharatMinds AI
 * 
 * This file defines the Appwrite database collections structure
 * Use this as a reference when creating collections in Appwrite Console
 */

// ============================================================================
// COUNSELLING ENUMS
// ============================================================================

export enum CounsellingType {
    UGCET = 'UGCET',
    UGNEET = 'UGNEET',
    COMBINED = 'COMBINED'
}

export enum BaseCategory {
    CATEGORY_1G = '1G',
    CATEGORY_2AG = '2AG',
    CATEGORY_2BG = '2BG',
    CATEGORY_3AG = '3AG',
    CATEGORY_3BG = '3BG',
    SC = 'SCG',
    ST = 'STG',
    GM = 'GM'
}

// ============================================================================
// COLLECTION: user_profiles
// ============================================================================

/**
 * User Profiles Collection Schema
 * 
 * Collection ID: user_profiles
 * Purpose: Extended user profile information beyond basic auth
 */
export interface UserProfileSchema {
    // Primary Key (auto-generated by Appwrite)
    $id?: string;

    // Foreign Key - Links to Appwrite Auth User
    userId: string; // Required, indexed, unique

    // Basic Info (synced from Auth)
    name: string; // Required
    email: string; // Required, indexed
    phone?: string;

    // Educational Background
    college?: string; // Index recommended for search
    city?: string;
    state?: string;
    currentYear?: string; // e.g., "12th", "1st Year"
    stream?: string; // e.g., "Science (PCM)", "Commerce"

    // Career Counselling
    examType?: string; // UGCET | UGNEET | COMBINED
    preferredLanguage?: string; // English | Kannada | Hindi | Telugu

    // Additional Contact
    guardianName?: string;
    guardianPhone?: string;

    // Metadata
    profileCompleted: boolean; // Default: false
    registrationCompleted: boolean; // Default: false

    // Timestamps (auto-managed by Appwrite)
    $createdAt?: string;
    $updatedAt?: string;
}

/**
 * Appwrite Collection Attributes for user_profiles:
 * 
 * 1. userId (string, 36, required, unique)
 * 2. name (string, 255, required)
 * 3. email (email, 255, required)
 * 4. phone (string, 20)
 * 5. college (string, 255)
 * 6. city (string, 100)
 * 7. state (string, 100)
 * 8. currentYear (string, 50)
 * 9. stream (string, 100)
 * 10. examType (enum: ['UGCET', 'UGNEET', 'COMBINED'])
 * 11. preferredLanguage (enum: ['English', 'Kannada', 'Hindi', 'Telugu'])
 * 12. guardianName (string, 255)
 * 13. guardianPhone (string, 20)
 * 14. profileCompleted (boolean, default: false)
 * 15. registrationCompleted (boolean, default: false)
 * 
 * Indexes:
 * - userId (unique)
 * - email
 * - college (for search)
 * - examType (for filtering)
 */

// ============================================================================
// COLLECTION: students
// ============================================================================

/**
 * Students Collection Schema
 * 
 * Collection ID: students
 * Purpose: Complete student registration data for counselling
 */
export interface StudentSchema {
    $id?: string;

    // User Reference
    userId: string; // Links to user_profiles

    // Personal Info
    name: string;
    mobile: string;
    email: string;

    // Counselling Information
    counsellingTypes: string[]; // Array of CounsellingType

    // UGCET Data
    ugcetCourses?: string[]; // Array of course names
    farmScienceCourses?: string[];

    // UGNEET Data
    ugneetCourses?: string; // JSON string of UGNEETCourseSelection[]
    ugneetSpecialCategories?: string[]; // Array of special categories
    neetAIR?: number; // All India Rank

    // Ranks (stored as JSON)
    courseRanks: string; // JSON string of CourseRank[]

    // Category Information
    baseCategory: string; // BaseCategory enum value
    hasKannada: boolean;
    hasRural: boolean;
    hasHK: boolean; // Hyderabad-Karnataka region
    snqApplied?: boolean; // SNQ Quota
    incomeSlab?: string;
    eligibleCategories: string; // JSON string of CategoryVariant[]
    specialCategories: string; // JSON string of SpecialCategory[]

    // Timestamps
    $createdAt?: string;
    $updatedAt?: string;
}

/**
 * Appwrite Collection Attributes for students:
 * 
 * 1. userId (string, 36, required)
 * 2. name (string, 255, required)
 * 3. mobile (string, 20, required)
 * 4. email (email, 255, required)
 * 5. counsellingTypes (string[], array)
 * 6. ugcetCourses (string[], array)
 * 7. farmScienceCourses (string[], array)
 * 8. ugneetCourses (string, 5000) - JSON
 * 9. ugneetSpecialCategories (string[], array)
 * 10. neetAIR (integer)
 * 11. courseRanks (string, 10000) - JSON
 * 12. baseCategory (string, 10)
 * 13. hasKannada (boolean, default: false)
 * 14. hasRural (boolean, default: false)
 * 15. hasHK (boolean, default: false)
 * 16. snqApplied (boolean)
 * 17. incomeSlab (string, 50)
 * 18. eligibleCategories (string, 5000) - JSON
 * 19. specialCategories (string, 1000) - JSON
 * 
 * Indexes:
 * - userId
 * - email
 * - mobile
 * - baseCategory (for filtering)
 */

// ============================================================================
// COLLECTION: option_lists
// ============================================================================

/**
 * Option Lists Collection Schema
 * 
 * Collection ID: option_lists
 * Purpose: Store generated college recommendations for students
 */
export interface OptionListSchema {
    $id?: string;

    // Student Reference
    studentId: string; // Links to students collection
    userId: string; // Links to user_profiles

    // Generated Options (stored as JSON)
    safeColleges: string; // JSON string of ScoredCollege[]
    targetColleges: string; // JSON string of ScoredCollege[]
    reachColleges: string; // JSON string of ScoredCollege[]

    // Metadata
    generatedAt: string;
    examType: string; // UGCET | UGNEET
    totalOptions: number;

    // Timestamps
    $createdAt?: string;
    $updatedAt?: string;
}

/**
 * Appwrite Collection Attributes for option_lists:
 * 
 * 1. studentId (string, 36, required)
 * 2. userId (string, 36, required)
 * 3. safeColleges (string, 50000) - JSON
 * 4. targetColleges (string, 50000) - JSON
 * 5. reachColleges (string, 50000) - JSON
 * 6. generatedAt (datetime)
 * 7. examType (enum: ['UGCET', 'UGNEET'])
 * 8. totalOptions (integer)
 * 
 * Indexes:
 * - studentId
 * - userId
 * - examType
 */

// ============================================================================
// PERMISSIONS GUIDE
// ============================================================================

/**
 * Recommended Permissions for Collections:
 * 
 * user_profiles:
 * - Create: users (any authenticated user)
 * - Read: user:{userId} (own profile only)
 * - Update: user:{userId} (own profile only)
 * - Delete: user:{userId} (own profile only)
 * 
 * students:
 * - Create: users
 * - Read: user:{userId}
 * - Update: user:{userId}
 * - Delete: user:{userId}
 * 
 * option_lists:
 * - Create: users
 * - Read: user:{userId}
 * - Update: user:{userId}
 * - Delete: user:{userId}
 */

// ============================================================================
// STORAGE BUCKETS
// ============================================================================

/**
 * PDF Bucket Configuration
 * 
 * Bucket ID: pdfs
 * Purpose: Store generated PDF reports for students
 * 
 * Attributes:
 * - Max file size: 10MB
 * - Allowed file extensions: ['pdf']
 * - Encryption: Yes
 * - Antivirus: Yes
 * 
 * Permissions:
 * - Create: users
 * - Read: user:{userId}
 * - Update: user:{userId}
 * - Delete: user:{userId}
 */

// Note: This module intentionally exports TypeScript types/enums only.
